# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/mghor004/final-project-bmcgh001-mghor004-wmont012

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/mghor004/final-project-bmcgh001-mghor004-wmont012

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/mghor004/final-project-bmcgh001-mghor004-wmont012/CMakeFiles /home/csmajs/mghor004/final-project-bmcgh001-mghor004-wmont012/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/mghor004/final-project-bmcgh001-mghor004-wmont012/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named menuTest

# Build rule for target.
menuTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 menuTest
.PHONY : menuTest

# fast build rule for target.
menuTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menuTest.dir/build.make CMakeFiles/menuTest.dir/build
.PHONY : menuTest/fast

GameMenu/menuMain.o: GameMenu/menuMain.cpp.o

.PHONY : GameMenu/menuMain.o

# target to build an object file
GameMenu/menuMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menuTest.dir/build.make CMakeFiles/menuTest.dir/GameMenu/menuMain.cpp.o
.PHONY : GameMenu/menuMain.cpp.o

GameMenu/menuMain.i: GameMenu/menuMain.cpp.i

.PHONY : GameMenu/menuMain.i

# target to preprocess a source file
GameMenu/menuMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menuTest.dir/build.make CMakeFiles/menuTest.dir/GameMenu/menuMain.cpp.i
.PHONY : GameMenu/menuMain.cpp.i

GameMenu/menuMain.s: GameMenu/menuMain.cpp.s

.PHONY : GameMenu/menuMain.s

# target to generate assembly for a file
GameMenu/menuMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menuTest.dir/build.make CMakeFiles/menuTest.dir/GameMenu/menuMain.cpp.s
.PHONY : GameMenu/menuMain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... menuTest"
	@echo "... GameMenu/menuMain.o"
	@echo "... GameMenu/menuMain.i"
	@echo "... GameMenu/menuMain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

